lidar_ros2_driver_node:
  ros__parameters:
    frame_id: laser_frame
    ip: 192.168.0.11
    port: 8090
    lidar_type: 0
    angle_min: -150.0
    angle_max: 150.0
    range_max: 30.0
    range_min: 0.01
    frequency: 20.0
    sample_rate: 34
    reversion: true
